# TODO Reenable once https://github.com/sisl/CUDD.jl/issues/15#issuecomment-719958808 is resolved
#include("BDD/BDD.jl")
#include("BDD/test_inttupleset.jl")
include("gol_lazar_belta.jl")
include("test_griddomain.jl")
include("test_controlsystemgrowth.jl")
include("test_controlsystemlinearized.jl")
include("test_automaton.jl")
include("test_symbolicmodel.jl")
include("test_fromcontrolsystemgrowth.jl")
include("test_fromcontrolsystemlinearized.jl")
include("test_controller.jl")
include("test_controllerreach.jl")
include("test_controllersafe.jl")
