#!/usr/bin/env julia
"""
Assemble benchmark results from JSON metrics files and produce a LaTeX report.

Usage:
    julia --project=<PROJECT> generate_report.jl [results_dir] [report_dir]

Reads all `metrics_*.json` files under results_dir (recursively) and generates
a LaTeX comparison report in report_dir.
"""

using JSON
using Dates
using Printf

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function find_json_files(dir::String)
    files = String[]
    for (root, _, filenames) in walkdir(dir)
        for f in filenames
            if startswith(f, "metrics_") && endswith(f, ".json")
                push!(files, joinpath(root, f))
            end
        end
    end
    return files
end

function load_results(results_dir::String)
    results = Dict{String, Vector{Dict{String, Any}}}()
    for f in find_json_files(results_dir)
        data = JSON.parsefile(f)
        mode = get(data, "mode", "unknown")
        if !haskey(results, mode)
            results[mode] = []
        end
        push!(results[mode], data)
    end
    return results
end

function latest_result(runs::Vector{Dict{String, Any}})
    sort!(runs; by = r -> get(r, "timestamp", ""), rev = true)
    return runs[1]
end

safe_get(d::Dict, key::String, default = "—") = get(d, key, default)

function fmt_time(sec)
    sec isa Number ? @sprintf("%.4f", sec) : string(sec)
end

function fmt_float(val; digits = 2)
    val isa Number ? @sprintf("%.*f", digits, val) : string(val)
end

function escape_latex(s::String)
    s = replace(s, "\\" => "\\textbackslash{}")
    s = replace(s, "&" => "\\&")
    s = replace(s, "%" => "\\%")
    s = replace(s, "\$" => "\\\$")
    s = replace(s, "#" => "\\#")
    s = replace(s, "_" => "\\_")
    s = replace(s, "{" => "\\{")
    s = replace(s, "}" => "\\}")
    s = replace(s, "~" => "\\textasciitilde{}")
    s = replace(s, "^" => "\\textasciicircum{}")
    return s
end

# ---------------------------------------------------------------------------
# LaTeX generation
# ---------------------------------------------------------------------------

function generate_latex(results::Dict{String, Vector{Dict{String, Any}}}, report_dir::String)
    modes = ["serial", "threaded", "distributed", "hybrid"]
    data = Dict{String, Dict{String, Any}}()

    for m in modes
        if haskey(results, m) && !isempty(results[m])
            data[m] = latest_result(results[m])
        end
    end

    if isempty(data)
        println("ERROR: No results found. Cannot generate report.")
        return nothing
    end

    tex = IOBuffer()

    # ── Preamble ──
    example_name = escape_latex(string(safe_get(first(values(data)), "example", "Dionysos")))

    println(tex, raw"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[margin=2.5cm]{geometry}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{xcolor}
\usepackage{colortbl}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{float}
\usepackage{caption}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{enumitem}
\usepackage{fancyhdr}

\setlength{\headheight}{14pt}
\addtolength{\topmargin}{-2pt}

\definecolor{headerblue}{RGB}{41,65,122}
\definecolor{lightgray}{RGB}{240,240,240}
\definecolor{successgreen}{RGB}{34,139,34}
\definecolor{warnorange}{RGB}{200,120,0}

\pagestyle{fancy}
\fancyhf{}
\rhead{Dionysos Parallel Benchmarks}
\lhead{\today}
\cfoot{\thepage}

\hypersetup{
    colorlinks=true,
    linkcolor=headerblue,
    urlcolor=headerblue,
}
""")
    println(
        tex,
        "\\title{\\textcolor{headerblue}{\\textbf{Dionysos Parallel Benchmark Report}}\\\\[0.5em]",
    )
    println(
        tex,
        "       \\large $(example_name): Serial vs.\\ Threaded vs.\\ Distributed vs.\\ Hybrid}",
    )
    println(tex, "\\author{Auto-generated by \\texttt{generate\\_report.jl}}")
    println(tex, "\\date{", escape_latex(string(Dates.now())), "}")
    println(tex, raw"""
\begin{document}
\maketitle
\tableofcontents
\newpage
""")

    # ── Section 1: Executive Summary ──
    println(tex, raw"""
\section{Executive Summary}
This report compares four parallelism strategies for Dionysos abstraction-based controller synthesis:
\begin{enumerate}[leftmargin=2em]
  \item \textbf{Serial} — single thread, single process (baseline).
  \item \textbf{Multithreaded} — multiple Julia threads within one process (\texttt{Threads.@threads}).
  \item \textbf{Distributed} — multiple Julia processes (workers) via \texttt{Distributed.jl} + \texttt{pmap}.
  \item \textbf{Hybrid} — multiple workers, each using multiple threads.
\end{enumerate}
The abstraction construction (computing the symbolic transition system) is the parallelized phase.
Each mode is controlled via the \texttt{DIONYSOS\_DISTRIBUTED} and \texttt{DIONYSOS\_THREADED} environment variables.
""")

    # ── Section 2: Environment ──
    println(tex, raw"\section{Environment}")
    sample = first(values(data))
    println(tex, raw"\begin{table}[H]")
    println(tex, raw"\centering")
    println(tex, raw"\caption{Runtime Environment}")
    println(tex, raw"\begin{tabular}{ll}")
    println(tex, raw"\toprule")
    println(tex, raw"\textbf{Property} & \textbf{Value} \\\\")
    println(tex, raw"\midrule")
    println(
        tex,
        "Julia version & \\texttt{",
        escape_latex(string(safe_get(sample, "julia_version"))),
        "} \\\\",
    )
    println(
        tex,
        "Hostname & \\texttt{",
        escape_latex(string(safe_get(sample, "hostname"))),
        "} \\\\",
    )
    println(tex, "Total memory & ", safe_get(sample, "total_memory_GB"), " GB \\\\")
    println(
        tex,
        "Example & \\texttt{",
        escape_latex(string(safe_get(sample, "example"))),
        "} \\\\",
    )

    for var in [
        "SLURM_JOB_ID",
        "SLURM_NNODES",
        "SLURM_NTASKS",
        "SLURM_CPUS_PER_TASK",
        "SLURM_NODELIST",
    ]
        val = safe_get(sample, var, nothing)
        if val !== nothing
            println(
                tex,
                escape_latex(var),
                " & \\texttt{",
                escape_latex(string(val)),
                "} \\\\",
            )
        end
    end
    println(tex, raw"\bottomrule")
    println(tex, raw"\end{tabular}")
    println(tex, raw"\end{table}")

    # ── Section 3: Results comparison table ──
    println(tex, raw"""
\section{Performance Comparison}
\subsection{Summary Table}
""")
    println(tex, raw"\begin{table}[H]")
    println(tex, raw"\centering")
    println(tex, raw"\caption{Benchmark Results — all modes}")
    println(tex, raw"\begin{tabular}{l r r r r r r}")
    println(tex, raw"\toprule")
    println(
        tex,
        raw"\textbf{Mode} & \textbf{Time (s)} & \textbf{Speedup} & \textbf{Threads} & \textbf{Workers} & \textbf{Parts} & \textbf{Alloc (MB)} \\\\",
    )
    println(tex, raw"\midrule")

    serial_time = nothing
    if haskey(data, "serial")
        serial_time = get(data["serial"], "elapsed_sec", nothing)
    end

    for m in modes
        haskey(data, m) || continue
        d = data[m]
        t = get(d, "elapsed_sec", 0.0)
        threads = get(d, "julia_threads", 1)
        nworkers_val = get(d, "julia_nworkers", 0)
        parts = get(d, "dionysos_nparts", 1)
        alloc = get(d, "alloc_MB", "—")

        speedup = "1.00"
        if serial_time !== nothing && serial_time > 0 && t > 0
            speedup = fmt_float(serial_time / t)
        end

        mode_label = Dict(
            "serial" => "Serial",
            "threaded" => "Threaded",
            "distributed" => "Distributed",
            "hybrid" => "Hybrid",
        )[m]
        println(
            tex,
            "$mode_label & $(fmt_time(t)) & $(speedup)\\texttimes & $threads & $nworkers_val & $parts & $alloc \\\\",
        )
    end

    println(tex, raw"\bottomrule")
    println(tex, raw"\end{tabular}")
    println(tex, raw"\end{table}")

    # ── Section 4: Detailed per-mode analysis ──
    println(tex, raw"\subsection{Detailed Metrics}")

    for m in modes
        haskey(data, m) || continue
        d = data[m]
        mode_label = Dict(
            "serial" => "Serial",
            "threaded" => "Multithreaded",
            "distributed" => "Distributed (Multiprocessing)",
            "hybrid" => "Hybrid (Distributed + Threaded)",
        )[m]

        # Compute speedup for this mode
        speedup_str = "—"
        if serial_time !== nothing && serial_time > 0
            t = get(d, "elapsed_sec", 0.0)
            if t > 0
                speedup_str = fmt_float(serial_time / t)
            end
        end

        println(tex, "\n\\subsubsection{$mode_label}")
        println(tex, raw"\begin{table}[H]")
        println(tex, raw"\centering")
        println(tex, raw"\begin{tabular}{ll}")
        println(tex, raw"\toprule")
        println(tex, raw"\textbf{Metric} & \textbf{Value} \\\\")
        println(tex, raw"\midrule")

        detail_keys = [
            ("elapsed_sec", "Wall-clock time (s)"),
            ("wall_clock_sec", "Total time incl. setup (s)"),
            ("julia_threads", "Julia threads"),
            ("julia_nprocs", "Julia processes"),
            ("julia_nworkers", "Julia workers"),
            ("dionysos_nparts", "Partitions (NPARTS)"),
            ("alloc_MB", "Allocated memory (MB)"),
            ("gc_time_sec", "GC time (s)"),
            ("free_memory_GB", "Free memory (GB)"),
            ("total_memory_GB", "Total memory (GB)"),
            ("hostname", "Hostname"),
            ("pid", "PID"),
        ]

        for (key, label) in detail_keys
            val = get(d, key, nothing)
            val === nothing && continue
            val_str = val isa Bool ? (val ? "Yes" : "No") : escape_latex(string(val))
            println(tex, "$label & \\texttt{$val_str} \\\\")
        end

        println(tex, "Speedup vs.~serial & \\texttt{$(speedup_str)\\texttimes} \\\\")

        # Worker details
        winfo = get(d, "worker_info", nothing)
        if winfo !== nothing && winfo isa Dict
            println(tex, raw"\midrule")
            println(tex, raw"\multicolumn{2}{l}{\textbf{Worker Details}} \\\\")
            for (wid, info) in winfo
                host = get(info, "host", "?")
                pid = get(info, "pid", "?")
                thr = get(info, "threads", "?")
                println(
                    tex,
                    "Worker $wid & host=\\texttt{$(escape_latex(string(host)))}, pid=$pid, threads=$thr \\\\",
                )
            end
        end

        nodes = get(d, "nodes_used", nothing)
        if nodes !== nothing && nodes isa Vector
            println(
                tex,
                "Nodes used & \\texttt{$(escape_latex(join(nodes, ", ")))} \\\\",
            )
        end

        # SLURM info
        has_slurm = false
        for var in [
            "SLURM_JOB_ID",
            "SLURM_NNODES",
            "SLURM_NTASKS",
            "SLURM_CPUS_PER_TASK",
            "SLURM_NODELIST",
        ]
            val = get(d, var, nothing)
            if val !== nothing
                if !has_slurm
                    println(tex, raw"\midrule")
                    println(
                        tex,
                        raw"\multicolumn{2}{l}{\textbf{SLURM Configuration}} \\\\",
                    )
                    has_slurm = true
                end
                println(
                    tex,
                    escape_latex(var),
                    " & \\texttt{",
                    escape_latex(string(val)),
                    "} \\\\",
                )
            end
        end

        println(tex, raw"\bottomrule")
        println(tex, raw"\end{tabular}")
        println(tex, raw"\end{table}")
    end

    # ── Section 5: Pros & Cons ──
    println(tex, raw"""
\section{Pros, Cons, and Recommendations}

\subsection{Serial}
\begin{itemize}[leftmargin=2em]
  \item[\textcolor{successgreen}{+}] Simplest code, no synchronization overhead, fully deterministic.
  \item[\textcolor{successgreen}{+}] No worker startup cost.
  \item[\textcolor{red}{--}] Does not exploit multicore hardware at all.
  \item[\textcolor{red}{--}] Abstraction construction time scales linearly with state-space size.
\end{itemize}
\textbf{Best for:} Small state spaces, debugging, baseline measurements.

\subsection{Multithreaded (\texttt{Threads.@threads})}
\begin{itemize}[leftmargin=2em]
  \item[\textcolor{successgreen}{+}] Shared-memory parallelism --- no data serialization cost.
  \item[\textcolor{successgreen}{+}] Easy to use; scales with \texttt{--threads=N}.
  \item[\textcolor{successgreen}{+}] Good speedup on single-node, multicore machines.
  \item[\textcolor{red}{--}] Limited to one machine (shared address space).
  \item[\textcolor{red}{--}] GC stop-the-world pauses affect all threads.
  \item[\textcolor{red}{--}] Thread-safety of user-defined dynamics must be ensured.
\end{itemize}
\textbf{Best for:} Single-node jobs; \texttt{--cpus-per-task} $\geq 4$.

\subsection{Distributed (\texttt{Distributed.jl})}
\begin{itemize}[leftmargin=2em]
  \item[\textcolor{successgreen}{+}] Scales across multiple nodes.
  \item[\textcolor{successgreen}{+}] Each worker has independent GC, memory, fault isolation.
  \item[\textcolor{successgreen}{+}] Natural fit for SLURM \texttt{--ntasks} across nodes.
  \item[\textcolor{red}{--}] Data must be serialized/deserialized for each worker (communication cost).
  \item[\textcolor{red}{--}] Worker startup and \texttt{@everywhere} loading add overhead.
  \item[\textcolor{red}{--}] The final transition merge runs on the master (bottleneck for large abstractions).
\end{itemize}
\textbf{Best for:} Multi-node clusters; large state spaces; embarrassingly parallel abstraction.

\subsection{Hybrid (Distributed + Threaded)}
\begin{itemize}[leftmargin=2em]
  \item[\textcolor{successgreen}{+}] Combines multi-node scaling with intra-node thread parallelism.
  \item[\textcolor{successgreen}{+}] Maximizes hardware utilization ($\text{workers} \times \text{threads}$).
  \item[\textcolor{red}{--}] Most complex configuration.
  \item[\textcolor{red}{--}] Requires careful SLURM tuning: \texttt{--ntasks} $\times$ \texttt{--cpus-per-task}.
  \item[\textcolor{red}{--}] Diminishing returns if communication dominates.
\end{itemize}
\textbf{Best for:} Large-scale HPC; very large state spaces; multi-node with multicore nodes.
""")

    # ── Section 6: SLURM cheat sheet ──
    println(tex, raw"""
\section{SLURM Configuration Cheat Sheet}

\begin{table}[H]
\centering
\caption{Recommended \texttt{sbatch} parameters per mode}
\begin{tabular}{l l l l l}
\toprule
\textbf{Mode} & \textbf{--nodes} & \textbf{--ntasks} & \textbf{--cpus-per-task} & \textbf{Julia flags} \\
\midrule
Serial      & 1 & 1 & 1          & (none) \\
Threaded    & 1 & 1 & 4--32      & \texttt{--threads=\$SLURM\_CPUS\_PER\_TASK} \\
Distributed & 1--N & 4--32 & 1   & (workers via \texttt{addprocs}) \\
Hybrid      & 1--N & 2--8  & 4--8 & \texttt{--threads=\$SLURM\_CPUS\_PER\_TASK} \\
\bottomrule
\end{tabular}
\end{table}

\textbf{Key rules:}
\begin{itemize}[leftmargin=2em]
  \item \texttt{DIONYSOS\_DISTRIBUTED=true} activates \texttt{Distributed.pmap} partitioned abstraction.
  \item \texttt{DIONYSOS\_THREADED=true} activates \texttt{Threads.@threads} within each process/worker.
  \item \texttt{DIONYSOS\_NPARTS} controls how the state space is partitioned across workers.
  \item Total cores = \texttt{ntasks} $\times$ \texttt{cpus-per-task} $\leq$ node cores $\times$ nodes.
  \item For threaded mode, set \texttt{JULIA\_NUM\_THREADS=\$SLURM\_CPUS\_PER\_TASK}.
  \item Use \texttt{--mem-per-cpu} for distributed/hybrid to scale memory with task count.
\end{itemize}
""")

    # ── Section 7: Scaling guidance ──
    println(tex, raw"""
\section{Scaling Guidance}

\begin{table}[H]
\centering
\caption{When to use each strategy}
\begin{tabular}{l l l}
\toprule
\textbf{Scenario} & \textbf{Recommended Mode} & \textbf{Rationale} \\
\midrule
Small state space, 1 node      & Serial           & Overhead exceeds benefit \\
Medium state space, 1 node     & Threaded          & Good speedup, minimal complexity \\
Large state space, multi-node  & Distributed       & Distributes memory pressure \\
Very large, multi-node         & Hybrid            & Maximizes all available hardware \\
\bottomrule
\end{tabular}
\end{table}
""")

    # ── End ──
    println(tex, raw"""
\section{Conclusion}
This benchmark demonstrates the effectiveness of the four parallelism strategies available
in Dionysos for abstraction-based controller synthesis.
The \texttt{UniformGridAbstraction.Optimizer} natively supports serial, threaded, distributed,
and hybrid execution modes via the \texttt{distributed} and \texttt{threaded} parameters.
The optimal strategy depends on the state-space size, available hardware, and the ratio of
computation to communication overhead.

\vfill
\begin{center}
\small
Generated on \today{} by \texttt{generate\_report.jl}\\
Dionysos Parallel Benchmark Suite
\end{center}

\end{document}
""")

    # Write to file
    tex_content = String(take!(tex))
    tex_path = joinpath(report_dir, "benchmark_report.tex")
    mkpath(report_dir)
    open(tex_path, "w") do io
        write(io, tex_content)
    end
    println("LaTeX report written to: $tex_path")

    # Try to compile
    try
        cd(report_dir) do
            run(`pdflatex -interaction=nonstopmode -halt-on-error benchmark_report.tex`)
            run(`pdflatex -interaction=nonstopmode -halt-on-error benchmark_report.tex`)
        end
        println(
            "PDF report generated: $(joinpath(report_dir, "benchmark_report.pdf"))",
        )
    catch e
        pdf_path = joinpath(report_dir, "benchmark_report.pdf")
        if isfile(pdf_path)
            println("PDF report generated (with warnings): $pdf_path")
        else
            println(
                "pdflatex not available or failed. LaTeX source is ready for manual compilation.",
            )
            println("  cd $report_dir && pdflatex benchmark_report.tex")
        end
    end

    return tex_path
end

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function main()
    script_dir = @__DIR__
    parallel_tests_dir = dirname(script_dir)

    results_dir = length(ARGS) >= 1 ? ARGS[1] : joinpath(parallel_tests_dir, "results")
    report_dir = length(ARGS) >= 2 ? ARGS[2] : joinpath(parallel_tests_dir, "report")

    println("=" ^ 60)
    println("  DIONYSOS BENCHMARK REPORT GENERATOR")
    println("=" ^ 60)
    println("  Results dir: $results_dir")
    println("  Report dir:  $report_dir")
    println()

    if !isdir(results_dir)
        println("ERROR: Results directory not found: $results_dir")
        println("Run the benchmarks first:")
        println("  bash parallel_tests/run_local.sh <example.jl>")
        exit(1)
    end

    json_files = find_json_files(results_dir)
    if isempty(json_files)
        println("ERROR: No metrics JSON files found in $results_dir")
        println("Make sure the benchmarks were run with the metrics wrapper.")
        exit(1)
    end

    results = load_results(results_dir)
    println("Found results for modes: $(collect(keys(results)))")
    for (mode, runs) in results
        println("  $mode: $(length(runs)) run(s)")
    end
    println()

    generate_latex(results, report_dir)
    println("\nDone.")
end

main()
